spring.application.name=portfolio

# "local" on your computer. Render will set SPRING_PROFILES_ACTIVE=prod
spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Render provides PORT. Locally we use 8081
server.port=${PORT:8081}